# These are supported funding model platforms

github: ['willtheorangeguy', 'Dog-Face-Development']
custom: ['https://paypal.me/wvdg44', 'https://psfmember.org/', 'https://www.pyinstaller.org/funding.html#funding-by-individuals']
