version = 1

test_patterns = ["tests/**"]

exclude_patterns = [
  "/build",
  "/dist"
]

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "docker"

[[transformers]]
name = "black"