language: python

python:
  - "3.5"

# command to install dependencies
before_install:
  - sudo apt-get update -qq

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - pip install sphinx coverage coveralls sphinx_rtd_theme
  - sudo apt-get install libavbin-dev libavbin0

install:
  - pip install -r requirements.txt

script:
  - python doc/preprocess_files.py
  - sphinx-build -b html doc doc/build/html
  - coverage run --source=arcade setup.py test

# deploy:
#   provider: pypi
#   user: $USERNAME
#   password: $PASSWORD
#   distributions: "bdist_wheel"

after_success:
  - coveralls
