name: "cla"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

jobs:
  CLAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document, and I hereby sign the CLA.') || github.event_name == 'pull_request_target'
        # Beta Release
        uses: contributor-assistant/github-action@v2.5.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # the below token should have repo scope and must be manually added by you in the repository's secret
          PERSONAL_ACCESS_TOKEN : ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          path-to-signatures: 'signatures/cla.json'
          path-to-document: 'https://github.com/Dog-Face-Development/.github/tree/main/docs/legal' # e.g. a CLA or a DCO document
          # branch should not be protected
          branch: 'main'
          allowlist: willtheorangeguy, bot*
          remote-organization-name: Dog-Face-Development
          remote-repository-name: cla-signatures
          create-file-commit-message: 'Create CLA signatures file'
          signed-commit-message: '$contributorName has signed the CLA in #$pullRequestNo'
          custom-notsigned-prcomment: 'Thank you for your contribution, please read and sign our CLA. Instructions on how to do so can be found in the `CONTRIBUTING.md` document.'
          custom-pr-sign-comment: 'I have read the CLA Document, and I hereby sign the CLA.'
          custom-allsigned-prcomment: 'All Contributors have signed the CLA!'
          
